"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
require("dotenv/config");
var config_1 = require("prisma/config");
exports.default = (0, config_1.defineConfig)({
    schema: "prisma/schema.prisma",
    migrations: {
        path: "prisma/migrations",
        seed: "tsx prisma/seed.ts",
    },
    datasource: {
        url: (0, config_1.env)("DATABASE_URL"),
    },
});
